### ISSUE TITLE
CurrencyTextField does not allow for more than 2 positions after decimal point

### ISSUE THREAD

**Issue by KevinOlive** [youjinp/SwiftUIKit#16]
This looked like it would work for the project I am working on where I need a currency field to be formatted/validated for a price per unit. however, i need values with at least 4 digits past the decimal. for example, $0.0475.

**Comment by youjinp** [comment]
I'm happy to merge in a pull request for that

**Comment by KevinOlive** [comment]
Hmmm, well. It looks like you’re offering for me to make that change—seems fair. I’ll have to see if I can figure that out. The concept seems simple enough but I’m not sure I’m experienced enough to figure that out yet. But I’ll look at it a bit more.

**Comment by youjinp** [comment]
Hi, just checking if you have looked into this / still need this?

**Comment by KevinOlive** [comment]
I haven’t made any progress on understanding how to update this. I’d still like to see that feature but it may be beyond my current skill.

**Comment by youjinp** [comment]
Alright thanks! I'll try to find some time implementing it within a week.

**Comment by youjinp** [comment]
Hi, I've added the option to specify the number of decimal points in release `v0.0.12`. Let me know if this solves your issue. Thanks!
